hw-05-lection-3-tooltip-component
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #11
Opened 2023-03-17 17:09 UTC by mushkovskiy

2023-03-17 17:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-18 10:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 21:22 UTC, GSemikozov requested changes

2023-03-18 21:22 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  position: absolute;
сам блок ни в коем случае не надо абсолютно позиционировать)

2023-03-19 11:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-19 11:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-04 19:58 UTC, GSemikozov approved these changes

2023-04-04 19:58 UTC, merged