hw-06-lection-4-avatar-component
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #15
Opened 2023-03-23 18:43 UTC by mushkovskiy

2023-03-23 18:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 08:04 UTC, GSemikozov requested changes

2023-03-24 08:04 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  position: relative;
строки 4-7 удалим

2023-03-29 18:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-01 11:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-04 20:02 UTC, GSemikozov approved these changes

2023-04-04 20:02 UTC, merged