Checkbox component
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #17
Opened 2023-04-09 12:12 UTC by mushkovskiy

2023-04-09 12:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-25 14:48 UTC, GSemikozov requested changes

2023-05-25 14:48 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.wrapper {
это ведь не часть данного блока, и - мы знаем что с такими врапперами делать)
актуально для всех ПР-ов где так делаем.

2023-06-06 20:43 UTC, GSemikozov approved these changes

2023-06-06 20:43 UTC, merged