hw-03-lection-1-button
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #4
Opened 2023-03-08 16:48 UTC by mushkovskiy

2023-03-08 16:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-09 13:44 UTC, GSemikozov requested changes

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +  --primaty-color: var(--blue);
это глобальная переменная

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary {
все общие стили для Кнопки описываются в классе блока, а в модификаторах, только то специфическое, чем кнопка будет отличаться от других

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary {
не хватает паддингов и стилей для описания текста

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary-hovered:hover {
.button_primary:hover

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary-disabled:disabled {
.button:disabled {}
+ pointer-events: none чтобы пользователь не мог нажимать

2023-03-09 13:44 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary__text {
лишних элемент, в нашей дизайн-системе нет вложенных элементов у кнопки

2023-03-09 15:07 UTC, mushkovskiy commented on 03-lection1/01-button/index.css
> +  --primaty-color: var(--blue);
Не очень понял, что здесь не так(( То что переменная глобальная, предполагает ее использование другим образом?

2023-03-09 15:17 UTC, mushkovskiy commented on 03-lection1/01-button/index.css
> +.button-primary {
То есть, получается вместо такого селектора .button-primary-hovered правильно вот так .button-primary_hovered?

2023-03-09 15:21 UTC, mushkovskiy commented on 03-lection1/01-button/index.css
> +.button-primary {
То есть получается что такого селектора быть не должно 
.button-secondary {
  --primaty-color: var(--purple);
  min-width: 182px;
  height: 48px;
  background: var(--primaty-color);
  border: none;
  border-radius: 8px;
  transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
}
должен быть модификатор для этого? Если да, то как тогда правильно он должен называться?

2023-03-10 08:51 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +  --primaty-color: var(--blue);
глобальные переменные размещает 1 раз в общем месте - это :root в main.css )

2023-03-10 08:52 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +.button-primary {
да, должно быть так:
```
.button {
   // общие стили
}
.button_primary {
    // то что модифицируем
    border-color: ...
    background-color: ...
    color: ...
}
```

2023-03-10 17:06 UTC, GSemikozov requested changes

2023-03-10 17:06 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +  padding: 15px 0 14px 0;
слева-справа тоже нужны (как проверить - добавить длинный текст)

2023-03-15 02:04 UTC, GSemikozov requested changes

2023-03-15 02:04 UTC, GSemikozov commented on 03-lection1/01-button/index.css
> +  padding: 15px 14px;
`15px 15px 14px;`

2023-03-18 21:17 UTC, GSemikozov approved these changes

2023-03-18 21:17 UTC, merged