hw-04-lection-2-sceleton-component
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #8
Opened 2023-03-12 13:40 UTC by mushkovskiy

2023-03-12 13:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 02:08 UTC, GSemikozov requested changes

2023-03-15 02:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 579px;
лишнее

2023-03-15 02:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  padding: 24px 0 32px 24px;
справа 40

2023-03-15 02:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
ширины у модификаторов лучше в процентах

2023-03-15 02:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton > .sceleton__item:last-child {
обязательно именно непосредственным дочерним .sceleton__item?

2023-03-15 17:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 17:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-15 18:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 21:19 UTC, GSemikozov approved these changes

2023-03-18 21:19 UTC, merged