hw-05-lection-3-calendar-component
js-tasks-ru/htmlcss-20230227_mushkov-es pull request #9
Opened 2023-03-16 20:44 UTC by mushkovskiy

2023-03-16 20:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 15:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-17 17:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 21:21 UTC, GSemikozov requested changes

2023-03-18 21:21 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  box-sizing: content-box;
точно ли именно так надо?)

2023-03-18 21:21 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 26px;
`28px 26px 32px`

2023-03-18 21:21 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  grid-row-gap: 20px;
24

2023-03-22 10:54 UTC, GSemikozov approved these changes

2023-03-22 10:54 UTC, merged